name: Run Build

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run
      run: go run main.go
      env:
        B2_KEYID: ${{ secrets.B2_KEYID }}
        B2_APPKEY: ${{ secrets.B2_APPKEY }}
