name: Run Build

on:
  schedule:
    # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run
        id: run
        run: go run main.go -dl -m=b2
        env:
          B2_KEYID: ${{ secrets.B2_KEYID }}
          B2_APPKEY: ${{ secrets.B2_APPKEY }}

      - name: Send workflow notification
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#hamcall\", \"username\": \"webhookbot\", \"text\": \"GitHub Action build result: ${{ job.status }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n```${{ steps.run.outputs.stdout }}```\", \"icon_emoji\": \":runner:\"}" ${{ secrets.SLACK_WEBHOOK }}
